### ISSUE TITLE
useSubscribe hook triggers rerendering loop

### ISSUE THREAD

**Issue by fmaul** [ostyjs/create-osty#2]
How ist the `useSubscribe()` hook meant to be used? When I do the following...
```typescript
import { useSubscribe } from "nostr-hooks";

const TestComponent = () => {

  const {events} = useSubscribe({
    filters: [
      {
        kinds: [1],
        limit: 10
      },
    ],
  });

  return <p>{events.length}</p>
}

export default TestComponent;
```

... a rerendering loop is created and I get the following error:  
```
Warning: Maximum update depth exceeded. This can happen when a component calls 
setState inside useEffect, but useEffect either doesn't have a dependency array, 
or one of the dependencies changes on every render.
```

Since  `useSubscribe()` returns an array of events I was expecting it to work this way. Is this a bug or just missing docs?

**Comment by sepehr-safari** [comment]
it's a bug. I'm working on it.

**Comment by sepehr-safari** [comment]
fixed https://github.com/ostyjs/create-osty/commit/491578a3b4cf46244ee9004a0ef68296b2dd94c7
could you please verify this fix? @fmaul

**Comment by fmaul** [comment]
That worked ... updated to `nostr-hooks` and my demo project did work!

**Comment by sepehr-safari** [comment]
thanks for the feedback mate 💜
