### ISSUE TITLE
login error: setSigner is not a function

### ISSUE THREAD

**Issue by wds4** [ostyjs/create-osty#9]
I am able to install osty successfully using `npm create osty@latest` and open the login page, but each time I try to login I get the error:
`setSigner is not a function`

So far I have tried this on linux ubuntu 22.04.4 and on macOS 12.5.1. On each, I have tried it using Alby and with a newly generated secret key. 

Anyone else getting this error?

**Comment by sepehr-safari** [comment]
FIXED in https://github.com/ostyjs/create-osty/commit/6f15e30443fc21e8a476c0a5f74c408525791fd0

could you please verify this fix?

**Comment by wds4** [comment]
Login with newly generated secret secret key works now on Linux and macOS 

Login with extension works on Linux and macOS 

👍🏻
